name: Pull Request
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  biome:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: setup mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
      - name: yarn install
        run: yarn install --immutable
      - name: biome ci
        run: yarn exec biome ci --reporter=github .

  proofdict-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: setup mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
      - name: yarn install
        run: yarn install --immutable
      - name: proofdict test
        run: yarn run test
